launch/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import RestaurantDetailView, RestaurantCreateView, RestaurantUpdateView, RestaurantDeleteView

app_name = "launch"

urlpatterns = [

    # Initial page when app launches
    path('', views.home, name='launch-home'),

    #Navbar limks
    path('about/', views.about, name='launch-about'), 
    path('contact/', views.contact, name='launch-contact'),
    path('blog-home/', views.blog_home, name='launch-bloghome'),
    path('blog-details/', views.blog_details, name='launch-blogdetails'), 

    # Page that loads when the user registers
    path('register/', views.register, name='register'),

    # Page that aks how to register. As a customer or register
    path('register-owner/', views.register_owner, name='register-owner'),
    path('register-customer/', views.register_customer, name='register-customer'),

    # Page that asks how to launch the page when logged in. As a customer or register
    path('owner-register/', views.owner_profile_view, name='launch-register-owner'),
    path('customer-register/', views.customer_profile_view, name='launch-register-customer'),
    
    # Paths to redirect towards log in and log out pages
    path('login/', auth_views.LoginView.as_view(template_name='launch/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='launch/logout.html'), name='logout'),

    # Path that shows the profile for customers or owner
    path('profile/', views.show_profile, name='profile'),

    #shows detail of restuarant using class based views
    path('restaurant/<int:pk>/', RestaurantDetailView.as_view(), name='restaurant-detail'), 

    #creates restuarant using class based views
    path('restaurant/new/', RestaurantCreateView.as_view(), name='restaurant-create'),

    path('restaurant/<int:pk>/update/', RestaurantUpdateView.as_view(), name='restaurant-update'),
    path('restaurant/<int:pk>/delete/', RestaurantDeleteView.as_view(), name='restaurant-delete')

]	

pickngo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('launch.urls', namespace='launch'))
]
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

launch/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse

# Class that sees whether the user is owner or customer
class User(AbstractUser):
    is_owner = models.BooleanField(default= True)

# Class for dealing with restaurant owner
class OwnerProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, related_name='owner_profile')
	image = models.ImageField(default='default.jpg', upload_to='profile_pics')

	def __str__(self):
		return self.user.username
  
# Class for dealing with customer
class CustomerProfile(models.Model):
  	user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, related_name='customer_profile')
  	image = models.ImageField(default='default.jpg', upload_to='profile_pics')

  	def __str__ (self):
  		return self.user.username

# Class for dealing with restaurants
class Restaurant(models.Model):
	name = models.CharField(max_length=100)
	location = models.CharField(max_length=300)
	cuisine = models.CharField(max_length=50)
	owner = models.ForeignKey(User, on_delete = models.CASCADE) #gets user from user tables. 
	image = models.ImageField(default='rest_default.jpg', upload_to='restaurant_pics')

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('launch:restaurant-detail', kwargs={'pk':self.pk})
	
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
	print('****', created)
	if instance.is_owner:
		OwnerProfile.objects.get_or_create(user = instance)

	else:
		CustomerProfile.objects.get_or_create(user = instance)
	
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
	print('_-----')	
	if instance.is_owner:
		instance.owner_profile.save()

	else:
		CustomerProfile.objects.get_or_create(user = instance)

launch/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms 
from django.contrib.auth.models import User
from .models import OwnerProfile
from .models import CustomerProfile
from django.contrib.auth import get_user_model
User = get_user_model()
CHOICES = ['Restaurant Owner', 'Customer']

# Form for registration of a user
class UserForm(UserCreationForm):
	first_name = forms.CharField()
	last_name = forms.CharField()
	email = forms.EmailField()
	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'email', 'username', 'password1', 'password2']

# Class to append the UserCreationForm for restaurant owner
class OwnerProfileForm(forms.ModelForm):
	images = forms.ImageField()
	class Meta:
		model = OwnerProfile
		fields = ['images']

# Class to append the UserCreationForm for 
class CustomerProfileForm(forms.ModelForm):
	images = forms.ImageField()
	class Meta:
		model = CustomerProfile
		fields = ['images']

# Class to update user form
class UserUpdateForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ['email']

# Class to update customer information
class CustomerUpdateForm(forms.ModelForm):
	class Meta:
		model = CustomerProfile
		fields = ['image']

# Class to update restaurant owner information
class OwnerUpdateForm(forms.ModelForm):
	class Meta:
		model = OwnerProfile
		fields = ['image']
        

launch/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView
from .forms import UserForm
from .forms import OwnerProfileForm
from .forms import CustomerProfileForm
from .forms import UserUpdateForm
from .forms import OwnerProfileForm
from .forms import CustomerUpdateForm
from .forms import OwnerUpdateForm
from .models import Restaurant 

class RestaurantDetailView(DetailView):
   model = Restaurant

class RestaurantCreateView(CreateView):
   model = Restaurant
   fields = ['name', 'location', 'cuisine', 'image']

   def form_valid(self,form):
      form.instance.owner = self.request.user
      return super().form_valid(form)

class RestaurantUpdateView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
   login_url = '/login/'
   model = Restaurant
   fields = ['name', 'location', 'cuisine', 'image']

   def form_valid(self,form):
      form.instance.owner = self.request.user
      return super().form_valid(form)

   def test_func(self):
      restaurant = self.get_object()
      if self.request.user == restaurant.owner:
         return True
      else:
         return False

class RestaurantDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
   model = Restaurant
   success_url = '/'
   def test_func(self):
      restaurant = self.get_object()
      if self.request.user == restaurant.owner:
         return True
      else:
         return False

# Function that works when launch page is accessed
def home(request):
   if request.user.is_authenticated:
      username = request.user.username

      if request.user.is_owner:
         context = {
            'restaurants': Restaurant.objects.all(),
            'myrestaurants': Restaurant.objects.filter(owner = request.user.id)
         }
         return render(request, 'launch/launch.html', context)

      else:
         context = {
            'restaurants': Restaurant.objects.all()   
         }
         return render(request, 'launch/launch.html',context)

   else:   
      return render(request, 'launch/launch.html')

# Navbar link functions
def about(request):
   return render(request, 'launch/about.html')

def contact(request):
   return render(request, 'launch/contact-us.html')

def blog_home(request):
   return render(request, 'launch/blog-home.html')

def blog_details(request):
   return render(request, 'launch/blog-details.html')

# Function for user registration
def register(request):
   return render(request, 'launch/register.html')

# Function that works when the chosen option is Restaurant owner
def register_owner(request):
   return render(request, 'launch/register-owner.html')

# Function that works when chosen option is customer owner
def register_customer(request):
   return render(request, 'launch/register-customer.html')

# Function that works then restuaurant owner registers
def owner_profile_view(request):
   if request.method == 'POST':
      user_form = UserForm(request.POST, prefix='UF')
      profile_form = OwnerProfileForm(request.POST, request.FILES, prefix='PF')

      if user_form.is_valid() and profile_form.is_valid():
         user = user_form.save(commit=False)
         user.save()
         username = user.username
         user.owner_profile.image = profile_form.cleaned_data.get('images')
         user.owner_profile.save()
         messages.success(request, f'Account created for {username}!')
         return redirect('launch:launch-home')
           
   else:
      user_form = UserForm(prefix='UF')
      profile_form = OwnerProfileForm(prefix='PF')
      
   return render(request, 'launch/register-owner.html',{
         'user_form': user_form,
         'profile_form': profile_form,
      })

# Function that works then customer registers
def customer_profile_view(request):
   if request.method == 'POST':
      user_form = UserForm(request.POST)
      profile_form = CustomerProfileForm(request.POST, request.FILES)

      if user_form.is_valid() and profile_form.is_valid():
         user = user_form.save(commit=False)
         user.is_owner = False
         user.save()
         user.customer_profile.image = profile_form.cleaned_data.get('images')
         user.customer_profile.save()

         username = user.username
         messages.success(request, f'Account created for {username}!')
         return redirect('launch:launch-home')
         
   else:
      user_form = UserForm(prefix='UF')
      profile_form = CustomerProfileForm(prefix='PF')
      
   return render(request, 'launch/register-customer.html',{
         'user_form': user_form,
         'profile_form': profile_form,
      })

# Function that works when either the customer or restauarant owner's profile is shown
def show_profile(request):
   if request.user.is_authenticated:
      if request.user.is_owner:

         if request.method == 'POST':
            u_form = UserUpdateForm(request.POST, instance = request.user)
            p_form =  OwnerUpdateForm(request.POST, request.FILES, instance = request.user.owner_profile)
            if u_form.is_valid() and p_form.is_valid():
               u_form.save()
               p_form.save()
               messages.success(request, f'Account has been update!')
               return redirect('launch:profile')

         else:
            u_form = UserUpdateForm(instance = request.user)
            p_form =  OwnerUpdateForm(instance = request.user.owner_profile)

         context = {
            'u_form': u_form,
            'p_form' : p_form
         }  
         return render(request, 'launch/profile.html',context)
 
      else:
         if request.method == 'POST':
            u_form = UserUpdateForm(request.POST, instance = request.user)
            p_form =  CustomerUpdateForm(request.POST, request.FILES, instance = request.user.customer_profile)
            if u_form.is_valid() and p_form.is_valid():
               u_form.save()
               p_form.save()
               messages.success(request, f'Account has been update!')
               return redirect('launch:profile')

         else:
            u_form = UserUpdateForm(instance = request.user)
            p_form =  CustomerUpdateForm(instance = request.user.customer_profile)

         context = {
            'u_form': u_form,
            'p_form' : p_form
         }  
         return render(request, 'launch/profile.html',context)

   else:
      return redirect('launch:launch-home')




   

launch/templates/launch/contact-us.html
{% extends 'launch/base.html' %}
{% load static %}

{% block title %}
    <title>Contact</title>
{% endblock %}

{% block header %}
    <!-- Preloader Starts -->
    <div class="preloader">
        <div class="spinner"></div>
    </div>
    <!-- Preloader End -->

   <!-- Header Area Starts -->
	<header class="header-area header-area2">
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <div class="logo-area">
                        <a href="index.html"><img src="{% static 'images/logo/logo2.png' %}" alt="logo"></a>
                    </div>
                </div>
                <div class="col-lg-10">
                    <div class="custom-navbar">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>  
                    <div class="main-menu main-menu2">
                        <ul>
                            <li class="active"><a href={% url 'launch:launch-home' %}>home</a></li>
                            <li><a href={% url 'launch:launch-about' %}>about</a></li>
                            <li><a href="#">blog</a>
                                <ul class="sub-menu">
                                    <li><a href={% url 'launch:launch-bloghome' %}>Blog Home</a></li>
                                    <li><a href={% url 'launch:launch-blogdetails' %}>Blog Details</a></li>
                                </ul>
                            </li>
                            <li><a href={% url 'launch:launch-contact' %}>contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Header Area End -->
{% endblock %}

{% block content %}
    <!-- Banner Area Starts -->
    <section class="banner-area banner-area2 contact-bg text-center">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1><i>Contact Us</i></h1>
                    <p class="pt-2"><i>Beast kind form divide night above let moveth bearing darkness.</i></p>
                </div>
            </div>
        </div>
    </section>
    <!-- Banner Area End -->

    <!-- Map Area Starts -->
    <section class="map-area section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div id="mapBox" class="mapBox" 
                        data-lat="40.701083" 
                        data-lon="-74.1522848" 
                        data-zoom="13" 
                        data-info="PO Box CT16122 Collins Street West, Victoria 8007, Australia."
                        data-mlat="40.701083"
                        data-mlon="-74.1522848">
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Map Area End -->


    <!-- Contact Form Starts -->
    <section class="contact-form section-padding3">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 mb-5 mb-lg-0">
                    <div class="d-flex">
                        <div class="into-icon">
                            <i class="fa fa-home"></i>
                        </div>
                        <div class="info-text">
                            <h5>California, United States</h5>
                            <p>Santa monica bullevard</p>
                        </div>
                    </div>
                    <div class="d-flex">
                        <div class="into-icon">
                            <i class="fa fa-phone"></i>
                        </div>
                        <div class="info-text">
                            <h5>00 (440) 9865 562</h5>
                            <p>Mon to Fri 9am to 6 pm</p>
                        </div>
                    </div>
                    <div class="d-flex">
                        <div class="into-icon">
                            <i class="fa fa-envelope-o"></i>
                        </div>
                        <div class="info-text">
                            <h5>support@colorlib.com</h5>
                            <p>Send us your query anytime!</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9">
                    <form action="#">
                        <div class="left">
                            <input type="text" placeholder="Enter your name" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter your name'" required>
                            <input type="email" placeholder="Enter email address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'" required>
                            <input type="text" placeholder="Enter subject" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter subject'" required>
                        </div>
                        <div class="right">
                            <textarea name="message" cols="20" rows="7"  placeholder="Enter Message" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Message'" required></textarea>
                        </div>
                        <button type="submit" class="template-btn">subscribe now</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Contact Form End -->
{% endblock %}

{% block footer %}
    <!-- Footer Area Starts -->
    <footer class="footer-area">
        <div class="footer-widget section-padding">
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <div class="single-widget single-widget1">
                            <a href="index.html"><img src="assets/images/logo/logo2.png" alt=""></a>
                            <p class="mt-3">Which morning fourth great won't is to fly bearing man. Called unto shall seed, deep, herb set seed land divide after over first creeping. First creature set upon stars deep male gathered said she'd an image spirit our</p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="single-widget single-widget2 my-5 my-md-0">
                            <h5 class="mb-4">contact us</h5>
                            <div class="d-flex">
                                <div class="into-icon">
                                    <i class="fa fa-map-marker"></i>
                                </div>
                                <div class="info-text">
                                    <p>1234 Some St San Francisco, CA 94102, US 1.800.123.4567 </p>
                                </div>
                            </div>
                            <div class="d-flex">
                                <div class="into-icon">
                                    <i class="fa fa-phone"></i>
                                </div>
                                <div class="info-text">
                                    <p>(123) 456 78 90</p>
                                </div>
                            </div>
                            <div class="d-flex">
                                <div class="into-icon">
                                    <i class="fa fa-envelope-o"></i>
                                </div>
                                <div class="info-text">
                                    <p>support@axiomthemes.com</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="single-widget single-widget3">
                            <h5 class="mb-4">opening hours</h5>
                            <p>Monday ...................... Closed</p>
                            <p>Tue-Fri .............. 10 am - 12 pm</p>
                            <p>Sat-Sun ............... 8 am - 11 pm</p>
                            <p>Holidays ............. 10 am - 12 pm</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7 col-md-6">
                        <span><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></span>
                    </div>
                    <div class="col-lg-5 col-md-6">
                        <div class="social-icons">
                            <ul>
                                <li class="no-margin">Follow Us</li>
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                                <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Area End -->
{% endblock %}

launch/templates/launch/launch.html
{% extends 'launch/base.html' %} 
{% load static %}
<!-- Page Title -->
{% block title %}
    <title>No Queue</title>
{% endblock  %}
    <!-- Header Area Starts -->
{% block header %}
  <header class="header-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <div class="logo-area">
                        <a href="index.html"><img src="{% static 'images/logo/logo.png' %}" alt="logo"></a>
                    </div>
                </div>
                <div class="col-lg-10">
                    <div class="custom-navbar">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>  
                    <div class="main-menu">
                        <ul>
                            <li class="active"><a href={% url 'launch:launch-home' %}>Home</a></li>
                            <li><a href={% url 'launch:launch-about' %}>About</a></li>
                            <li><a href={% url 'launch:launch-contact' %}>contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}
    <!-- Header Area End -->

{% block content %}
    {% if user.is_authenticated %}
        <h1>Welcome</h1> 
        <h3>{{user.get_username}}</h3>
        <a href={% url 'launch:logout' %}><button type="submit"> Logout </button></a>

        {% if user.is_owner %}
          <img width="100" height="100"src="{{user.owner_profile.image.url}}"></img>
          <h4> Restaurant owner</h4>

          {% if myrestaurants %}
            <h1>My Restaurants</h1>
            {% for restaurant in myrestaurants %}
              <div class="restaurant-container">
                <p><a href="{% url 'launch:restaurant-detail' restaurant.id%}">{{ restaurant.name }}</a></p>
                <img width="100" height="100" src="{{restaurant.image.url}}"></img>
                <p>{{ restaurant.cuisine }}</p>
                <p>{{ restaurant.location }}</p>        
              </div>
            {% endfor %}

        {% endif %}
        <a href={% url 'launch:restaurant-create' %}><button type="submit"> Add restaurant </button></a>

        {% else %}
        <h4> Customer </h4>
        <img width="100" height="100" src="{{user.customer_profile.image.url}}"></img>
        <h1>Restaurants</h1>

        {% for restaurant in restaurants %}
        <div class="restaurant-container">
          <p><a href="{% url 'launch:restaurant-detail' restaurant.id%}">{{ restaurant.name }}</a></p>
          <img width="100" height="100" src="{{restaurant.image.url}}"></img>
          <p>{{ restaurant.cuisine }}</p>
          <p>{{ restaurant.location }}</p>         
        </div>
        {% endfor %}   
    {% endif %}

    {% else %}
    <!-- Banner Area Starts -->
    <section class="banner-area text-center">
        <div class="container">
      <div class="background">
                <div class="layer"></div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <h1>Welcome to  <span class="prime-color">NoQueue!</span><br>  
                    <h6 style="">Never Wait in Line again!</h6>
            </br><a href={% url 'launch:login' %} class="genric-btn primary circle" >Log In</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <a href={% url 'launch:register' %} class="genric-btn primary circle">Register</a>
            </h1>
                </div>
            </div>
        </div>
    </section>
    {% endif %}
    <!-- Banner Area End -->
{% endblock %}

{% block footer %}
  <div class="footer-copyright">
    <div class="container">
      <div class="row">
        <div class="col-lg-7 col-md-6">
            <span><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made  by Group 3
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></span>
        </div>
          <div class="col-lg-5 col-md-6">
            <div class="social-icons">
              <ul>
                <li class="no-margin">Follow Us</li>
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                <li><a href="#"><i class="fa fa-instagram"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}


    
 

launch/templates/launch/login.html
{% extends 'launch/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
   <title>owner Log In</title>
{% endblock %}

{% block content %}
   <div>
      <h1>Login to owner</h1>
      <form method="POST">
         {% csrf_token %}
         <fieldset>
            <legend>Log In</legend>
            {{ form | crispy }}
         </fieldset>
         <button type="submit">Sign In</button>
      </form>
   </div>

   <div>
      <small>Need an account? <a href={% url 'launch:register' %}>Sign Up</a></small>
   </div>
{% endblock %}

launch/templates/launch/logout.html
{% extends "launch/base.html"%}
{% block title %}
   <h2> You have been logged out</h2>
   <a href="{% url 'launch:launch-home'%}"> Click here to log back in!</a>
{% endblock %}

launch/templates/launch/profile.html
{% extends 'launch/base.html' %}
{% block title %}
{% load crispy_forms_tags %}
   <title>Restaurant Register</title>
{% endblock %}

{% block content %}
   <div class="profile-container">  
      {% if user.is_owner %}
         <img width="100" height="100"src="{{user.owner_profile.image.url}}"></img>
         <h1>{{user.get_username}}</h1>
         <h4> Restaurant owner</h4>

      {% else %}
         <img width="100" height="100" src="{{user.customer_profile.image.url}}"></img>
         <h1>{{user.get_username}}</h1>
         <h4>Customer</h4>
      {% endif %}
   </div>

   <div class="update-container">
      <h1>Update Information</h1>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ u_form | crispy }}
        {{ p_form | crispy }}
         <button type="submit">Update</button>
      </form>
   </div>
{% endblock %}

launch/templates/launch/register-customer.html
{% extends 'launch/base.html' %}
{% block title %}
{% load crispy_forms_tags %}
   <title>Restaurant Register</title>
{% endblock %}

{% block content %}
   <div>
      <h1>Register Customer </h1>
      <form method="post" enctype="multipart/form-data" >
        {% csrf_token %}
            {{ user_form | crispy }}
            {{ profile_form | crispy }}
         <button type="submit">Sign Up</button>
      </form>
   </div>

   <div>
      <small>Already have an account? <a href={% url 'launch:login' %}>Sign In</a></small>
   </div>
{% endblock %}

launch/templates/launch/register-owner.html
{% extends 'launch/base.html' %}
{% block title %}
{% load crispy_forms_tags %}
   <title>owner Register</title>
{% endblock %}

{% block content %}
   <div>
      <h1>Register to owner</h1>
      <form method="post" enctype="multipart/form-data">
         {% csrf_token %}
         {{ user_form | crispy }}
         {{ profile_form | crispy }}
         <button type="submit">Sign Up</button>
      </form>
   </div>

   <div>
      <small>Already have an account? <a href={% url 'launch:login' %}>Sign In</a></small>
   </div>

{% endblock %}

launch/templates/launch/register.html
{% extends "launch/base.html"%}
{% block title %}
   <title>Launch-Home</title>
{% endblock %}

{% block content %}
   <h1>Register</h1>
   <a href={% url 'launch:launch-register-owner' %}><button type="submit">Owner</button></a>
   <a href={% url 'launch:launch-register-customer' %}><button type="submit">Customer</button></a>   
{% endblock %}
   

launch/templates/launch/restaurant_detail.html
{% extends "launch/base.html"%}
{% block title %}
   <title>Launch-Home</title>
{% endblock %}
{% block content %}
<<<<<<< HEAD
    <h1>Detail</h1>
    <div class="restaurant-container">
      <p>{ object.name }}</p>
      <img width="100" height="100" src="{{object.image.url}}"></img>  	     
      <p>{{ object.cuisine }}</p>
      <p>{{ object.location }}</p>
      <p>{{ object.owner }}</p>
      <p><a href="{% url 'launch:restaurant-update' object.id%}"> Edit </a></p>
      <p><a href="{% url 'launch:restaurant-delete' object.id%}"> Delete </a></p>
      <a href="{% url 'launch:launch-home'%}"><button>Back</button></a>           		
    </div>
=======
   <h1>Detail</h1>
   <div class="restaurant-container">
    <p>{ object.name }}</p>
    <img width="100" height="100" src="{{object.image.url}}"></img>  	     
    <p>{{ object.cuisine }}</p>
     <p>{{ object.location }}</p>
    <p>{{ object.owner }}</p>
    <p><a href="{% url 'launch:restaurant-update' object.id%}"> Edit </a></p>
    <p><a href="{% url 'launch:restaurant-delete' object.id%}"> Delete </a></p>
    <a href="{% url 'launch:launch-home'%}"><button>Back</button></a>           
    		
  </div>
>>>>>>> 88a551558f9b90abbddffe5dec045a6938d43e16
{% endblock %}